spring:
  application:
    name: baseplatform-system-server
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/base_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.sly.baseplatform.common.model
